#!/usr/bin/env python3
"""Writes the squircle as a set of stencils the graphics library can use.

The design's shape is a superellipse, |x|^n + |y|^n = 1, and the graphics
library draws only rectangles with a corner radius. So the shape comes in as an
image with nothing but an alpha channel, and whatever colour is wanted is shown
through it.

One stencil per size that the design actually uses. They are small: a stencil
is one byte a pixel, and all of them together are thirty kilobytes.

    python3 tools/generate_squircles.py

Writes src/squircles.cc, which the component compiles in.
"""

from __future__ import annotations

import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TOKENS = ROOT / "tokens" / "caliper.toml"
OUTPUT = ROOT / "src" / "squircles.cc"

#: The sizes a squircle is drawn at. Stated rather than derived, because the
#: places that use one are counted and a stencil for a size nobody asks for is
#: bytes nobody gets back.
SIZES = (50, 66)

#: How many samples across one pixel, for the edge. Four by four is enough that
#: the curve reads as smooth at this size and cheap enough to compute here.
SAMPLES = 4


def alpha(size: int, exponent: float) -> bytes:
    """One stencil: how opaque each pixel of a square of this size is.

    @param size How many points across and down.
    @param exponent The n of the superellipse.
    @returns One byte a pixel, row by row.
    """
    half = size / 2
    out = bytearray()
    for row in range(size):
        for column in range(size):
            inside = 0
            for sub_row in range(SAMPLES):
                y = (row + (sub_row + 0.5) / SAMPLES - half) / half
                for sub_column in range(SAMPLES):
                    x = (column + (sub_column + 0.5) / SAMPLES - half) / half
                    if abs(x) ** exponent + abs(y) ** exponent <= 1.0:
                        inside += 1
            out.append(round(255 * inside / (SAMPLES * SAMPLES)))
    return bytes(out)


def main() -> int:
    """Writes every stencil and says what came out."""
    exponent = tomllib.loads(TOKENS.read_text(encoding="utf-8"))["radius"]["squircle"]

    parts = ['''// Generated by tools/generate_squircles.py from tokens/caliper.toml.
// Do not edit: run it again.
//
// The design's shape is a superellipse and the graphics library draws only
// rectangles with a corner radius, so the shape comes in as a stencil and the
// colour is shown through it.

#include "caliper/shapes.h"
''']

    for size in SIZES:
        pixels = alpha(size, exponent)
        rows = ["    " + ", ".join(f"0x{byte:02x}" for byte in pixels[start:start + 16]) + ","
                for start in range(0, len(pixels), 16)]
        parts.append(f'''
static const uint8_t squircle_{size}_map[] = {{
{chr(10).join(rows)}
}};

static const lv_image_dsc_t squircle_{size} = {{
    .header = {{
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_A8,
        .flags = 0,
        .w = {size},
        .h = {size},
        .stride = {size},
        .reserved_2 = 0,
    }},
    .data_size = sizeof(squircle_{size}_map),
    .data = squircle_{size}_map,
    .reserved = NULL,
}};
''')

    table = ",\n".join(f"    {{{size}, &squircle_{size}}}" for size in SIZES)
    parts.append(f'''
namespace cal {{
namespace {{

struct Stencil {{
   std::int32_t size;
   const lv_image_dsc_t* mask;
}};

constexpr Stencil kStencils[] = {{
{table}}};

}}  // namespace

const lv_image_dsc_t* SquircleMask(std::int32_t size) {{
   for (const Stencil& each : kStencils) {{
      if (each.size == size) {{
         return each.mask;
      }}
   }}
   return nullptr;
}}

}}  // namespace cal
''')
    OUTPUT.write_text("".join(parts), encoding="utf-8")
    print(f"{len(SIZES)} stencils, {sum(size * size for size in SIZES)} bytes  {OUTPUT.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
